name = "hai-nlp-workshop"
compatibility_date = "2024-01-01"

pages_build_output_dir = "dist"

# Cloudflare Pages用の設定
# kiyo.dev/nlp/ でアクセス可能にする
[env.production]
routes = [
  { pattern = "kiyo.dev/nlp/*", zone_name = "kiyo.dev" }
]
